### ISSUE TITLE
&000d;

### ISSUE THREAD

**Issue by thomasdeanwhite** [djpaterson/PieTimer#2]
&000d;

**Comment by djpaterson** [comment]
Hi Thomas,
I am sorry to hear that you are having issues with Pie Timer v1.0
I would, however, contest your indication that there is **literally** nothing you can do to get it working - this software relies on the espeak command which is available in the linux repositories, and can be installed, as indicated, by running:
`sudo apt-get install espeak`
I hope this helps,
Regards,
Dave

**Comment by thomasdeanwhite** [comment]
I'm confronted with the following command:

`[sudo] password for thomas: `

**Comment by djpaterson** [comment]
If you enter your Linux Password in this field, it will allow you to run sudo commands.
For more information about using sudo on Linux, see [here](https://www.linux.com/blog/how-use-sudo-and-su-commands-linux-introduction)
