### ISSUE TITLE
.class

### ISSUE THREAD

**Issue by jose** [djpaterson/PieTimer#3]
Please help GitHub by removing the 3.16 KB class file.

**Comment by djpaterson** [comment]
Hi Jose,
Thanks for your suggestion.
This will be implemented in Pie Timer v1.1, which should be coming any time soon. Thanks for your patience with this.
Regards,
Dave

**Comment by djpaterson** [comment]
Hi Jose, great news!
Pie Timer v1.1 is now on github! New features include

1. Removed 3.16 KB class file from repository to help GitHub

Thanks for helping the PieTimer community!
Dave

**Comment by jose** [comment]
Great, many thanks.
